### ISSUE TITLE
How to install it ?

### ISSUE THREAD

**Issue by alidz1982** [MichaelBelgium/flarum-discussion-views#1]
How to install this add-on with a simple explanation .. and thank you

**Comment by MichaelBelgium** [comment]
It's not done yet, i'm currently working in the other branch either  way, but I believe it'll be ready this weekend. Maybe even in a few hours.

**Comment by MichaelBelgium** [comment]
@alidz1982 It's done

`composer require michaelbelgium/flarum-discussion-views`
