### ISSUE TITLE
Hiding view number from non-member users option

### ISSUE THREAD

**Issue by ayyilmaz** [MichaelBelgium/flarum-discussion-views#19]
I think hiding views numbers option from non-member users is effective and neccessary. This data is valuable. Everyone should not see.

**Comment by MichaelBelgium** [comment]
So basicly a new permission whether u can see the number of views or not?

**Comment by ayyilmaz** [comment]
Yes, some users like admin trnslator etc. can see but others hould not see this data. I think it is good option if we set its permission on admin panel.
