### ISSUE TITLE
SPA crash when trying to load discussion lower down

### ISSUE THREAD

**Issue by clarkwinkelmann** [MichaelBelgium/flarum-discussion-views#38]
I have not experienced this bug myself but I can see it while investigating this report by a Discuss user https://discuss.flarum.org/d/32514-email-notification-url-leads-to-a-broken-page

The discussion page appears broken (header and scrubber visible, remaining of the page blank)

The javascript console shows

```
TypeError: e.posts()[0] is undefined
    <anonymous> AddLists.js:56
    e extend.ts:39
    [...]
```

This trace points to line 56 here:

https://github.com/MichaelBelgium/flarum-discussion-views/blob/e8bdc1d289616219a83e43035ea41489fc23c980/js/src/forum/components/AddLists.js#L55-L56

The problem is that the code assumes that if `discussion.posts().length` is `> 0`, `[0]` will be an instance of `Post`. But it's not the case. Once loaded, the `posts()` relationship always returns an array the length of the discussion, with `Post` instances within the loaded range, and `undefined` outside the loaded range.

When loading a discussion via direct link, Flarum only loads the specified range (10 posts before and after the given target), so index 0 might not be loaded.

This problem doesn't occur when navigating from the homepage, even if the link leads to the bottom of the discussion because the homepage hydrates the `discussion.firstPost()` relationship which causes `[0]` to be available as well. But direct access to the discussion doesn't include `firstPost` relationship unless an extension explicitly add it so it's not available.

My suggestion to fix this issue would be to use the `ApiController` extender to add `firstPost` as an include on `ShowDiscussionController`. The code can then also be refactored to read the ID from that relationship instead of the `posts` relationship.

Or if knowing which post is the first post when it's out of range is not important (just looking at that method, it looks like it would not matter), the statement should be refactored to account for `undefined` value. The check for `length` can be dropped. When scrolling to the top, the value would become available once index 0 is within visible range.

**Comment by MichaelBelgium** [comment]
So if someone goes to /discussions/25 directly, only posts 15 to 35 gets loaded and `discussion.posts()[0]` doesn't exists? I mean yeah that makes sense. I only need add footeritems to the first post only
