### ISSUE TITLE
Use IP provided by http header instead of $_SERVER

### ISSUE THREAD

**Issue by edgeinfinity1** [MichaelBelgium/flarum-discussion-views#39]
When my server running flarum is behind a NAT server, the U/V function only records the IP of proxy, and I sometimes see errors like `flarum.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip' cannot be null in /www/wwwroot/192.168.5.132/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117`, which prevents realtime plugins to function, even turning U/V off does not work.

**Comment by Burial0268** [comment]
It seems that is because the developer use `$_SERVER['REMOTE_ADDR']` as the value of ip, which is a typically bad practice

However, Flarum provides a pecial way to get the client IP

https://github.com/MichaelBelgium/flarum-discussion-views/blob/master/src/Listeners/AddDiscussionViewHandler.php#L38-L53

@MichaelBelgium

**Comment by MichaelBelgium** [comment]
the invoke function does not have access to any client ip. It has to be `$_SERVER`

The `$request`variable only has generic headers available like referer, accept, user-agent, cookie, etc

Only thing i can think of is using another key in `$_SERVER` that does have the client's ip, which is probably located in
* HTTP_CLIENT_IP
or
* HTTP_X_FORWARDED_FOR

**Comment by MichaelBelgium** [comment]
I'll create a small update that gets the ip from either

* REMOTE_ADDR
* HTTP_CLIENT_IP
* HTTP_X_FORWARDED_FOR

And you'll have to see if that covers it

**Comment by Burial0268** [comment]
```
$clientIp = Arr::get($request->getServerParams(),'HTTP_X_FORWARDED_FOR',Arr::get($request->getServerParams(), 'REMOTE_ADDR'));
```

i think this might better than your fix
