### ISSUE TITLE
Use getServerParams instead of $_SERVER

### ISSUE THREAD

**Issue by YUCLing** [MichaelBelgium/flarum-discussion-views#40]
I'm setting up Swoole for my Flarum instance. However, I'm encountering some issues with this extension.

In Swoole, I have created a server param array and passed it to Laravel's request interface. But this plugin doesn't use it, it uses `$_SERVER` which has no values in this environment, causing my Flarum to complain about it.

``Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ip' cannot be null (SQL: insert into `forum_discussion_views` (`discussion_id`, `ip`, `visited_at`) values (236, ?, 2024-04-20 14:44:46)) in /var/www/web/vendor/illuminate/database/Connection.php:712``

**Comment by MichaelBelgium** [comment]
I pushed an update 15 minutes ago with a possible fix, are you on v7.2.2 ?

**Comment by YUCLing** [comment]
> a possible fix

That was not a fix for me. As I claimed, my environment has no values in `$_SERVER`.

**Comment by YUCLing** [comment]
FYI: Flarum core itself has a middleware that processes the user IP [here](https://github.com/flarum/framework/blob/9149ecc7aad62c592c070664c1ec503b025a9e00/framework/core/src/Http/Middleware/ProcessIp.php#L18).

**Comment by MichaelBelgium** [comment]
Yeah but it could be that REMOTE_ADDR can be null, according to #39 

Either way, check out v7.2.3
