### ISSUE TITLE
View Count Goes Up on Refresh

### ISSUE THREAD

**Issue by Spacella** [MichaelBelgium/flarum-discussion-views#9]
When you refresh the page while on the same account, it updates the view count. I was wondering if there was an option/an option to be implemented where I could make it where when you views discussion, it only updates the count on your first view.

**Comment by MichaelBelgium** [comment]
It's possible to make that, but not planning it yet. I'll add it in the future but I don't know when.

**Comment by Spacella** [comment]
Okay! The Songoda Community appreciates it! Thank you for making this plugin.

**Comment by ShiroNje** [comment]
Same problem seems site bad, can you make please.
